title: Sascha Triller
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.thetinker.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Sascha Triller'
  last_name: 'Triller'
  #cv: '//kaptn.ru'
  avatar: '/images/avatar.jpeg'
  github_username:  striller
  email: sascha.triller@posteo.de
  #vk_id: id201664979
  #telegram_name: vikapitoshka
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


